INSERT INTO account (id, email, password, user_name, phone_number, account_type) values (99, 'admin@gmail.com', '$2a$10$i1jipaZ9r07F21OdMVS6ZO/.0gW1dxtzrsEI2BemA69UOJuGXzYgG', 'admin', '010-0000-0000', 'ADMIN');
INSERT INTO account (id, email, password, user_name, phone_number, account_type) values (100, 'user@gmail.com', '$2a$10$i1jipaZ9r07F21OdMVS6ZO/.0gW1dxtzrsEI2BemA69UOJuGXzYgG', 'user', '010-0000-1111', 'USER');

INSERT INTO category (id, title, parent_id, deleted) values (1, '밑반찬', null, false);
INSERT INTO category (id, title, parent_id, deleted) values (2, '국·찌개', null, false);
INSERT INTO category (id, title, parent_id, deleted) values (3, '메인반찬', null, false);
INSERT INTO category (id, title, parent_id, deleted) values (4, '아이반찬', null, false);
INSERT INTO category (id, title, parent_id, deleted) values (5, '정기식단', null, false);
INSERT INTO category (id, title, parent_id, deleted) values (6, '신선·가공', null, false);
INSERT INTO category (id, title, parent_id, deleted) values (7, '간식', null, false);
INSERT INTO category (id, title, parent_id, deleted) values (8, '브랜드관', null, false);
INSERT INTO category (id, title, parent_id, deleted) values (9, '무침', 1, false);
INSERT INTO category (id, title, parent_id, deleted) values (10, '나물무침', 1, false);
INSERT INTO category (id, title, parent_id, deleted) values (11, '볶음', 1, false);
INSERT INTO category (id, title, parent_id, deleted) values (12, '조림', 1, false);
INSERT INTO category (id, title, parent_id, deleted) values (13, '김치', 1, false);
INSERT INTO category (id, title, parent_id, deleted) values (14, '전', 1, false);
INSERT INTO category (id, title, parent_id, deleted) values (15, '튀김', 1, false);
INSERT INTO category (id, title, parent_id, deleted) values (16, '장아찌·피클', 1, false);
INSERT INTO category (id, title, parent_id, deleted) values (17, '샐러드', 1, false);
INSERT INTO category (id, title, parent_id, deleted) values (18, '김', 1, false);
INSERT INTO category (id, title, parent_id, deleted) values (19, '젓갈·장·소스', 1, false);
INSERT INTO category (id, title, parent_id, deleted) values (20, '세트', 1, false);
INSERT INTO category (id, title, parent_id, deleted) values (21, '담백한국', 2, false);
INSERT INTO category (id, title, parent_id, deleted) values (22, '얼큰한국', 2, false);
INSERT INTO category (id, title, parent_id, deleted) values (23, '찌개', 2, false);
INSERT INTO category (id, title, parent_id, deleted) values (24, '탕', 2, false);
INSERT INTO category (id, title, parent_id, deleted) values (25, '전골', 2, false);
INSERT INTO category (id, title, parent_id, deleted) values (26, '세트', 2, false);
INSERT INTO category (id, title, parent_id, deleted) values (27, '고기반찬', 3, false);
INSERT INTO category (id, title, parent_id, deleted) values (28, '해산물반찬', 3, false);
INSERT INTO category (id, title, parent_id, deleted) values (29, '생선반찬', 3, false);
INSERT INTO category (id, title, parent_id, deleted) values (30, '덮밥', 3, false);
INSERT INTO category (id, title, parent_id, deleted) values (31, '면', 3, false);
INSERT INTO category (id, title, parent_id, deleted) values (32, '모던한식', 3, false);
INSERT INTO category (id, title, parent_id, deleted) values (33, '양식', 3, false);
INSERT INTO category (id, title, parent_id, deleted) values (34, '일식·중식', 3, false);
INSERT INTO category (id, title, parent_id, deleted) values (35, '분식', 3, false);
INSERT INTO category (id, title, parent_id, deleted) values (36, '죽·스프', 3, false);
INSERT INTO category (id, title, parent_id, deleted) values (37, '세트', 3, false);
INSERT INTO category (id, title, parent_id, deleted) values (38, '이유식 초기/중기', 4, false);
INSERT INTO category (id, title, parent_id, deleted) values (39, '이유식 후기/완료기', 4, false);
INSERT INTO category (id, title, parent_id, deleted) values (40, '아이반찬', 4, false);
INSERT INTO category (id, title, parent_id, deleted) values (41, '어린이반찬', 4, false);
INSERT INTO category (id, title, parent_id, deleted) values (42, '프리미엄재료', 4, false);
INSERT INTO category (id, title, parent_id, deleted) values (43, '1~2인', 5, false);
INSERT INTO category (id, title, parent_id, deleted) values (44, '3~4인', 5, false);
INSERT INTO category (id, title, parent_id, deleted) values (45, '아이반찬', 5, false);
INSERT INTO category (id, title, parent_id, deleted) values (46, '가공반찬', 6, false);
INSERT INTO category (id, title, parent_id, deleted) values (47, '가공간식', 6, false);
INSERT INTO category (id, title, parent_id, deleted) values (48, '냉동', 6, false);
INSERT INTO category (id, title, parent_id, deleted) values (49, '고기·생선', 6, false);
INSERT INTO category (id, title, parent_id, deleted) values (50, '과일·채소·양곡', 6, false);
INSERT INTO category (id, title, parent_id, deleted) values (51, '식사빵', 7, false);
INSERT INTO category (id, title, parent_id, deleted) values (52, '간식빵', 7, false);
INSERT INTO category (id, title, parent_id, deleted) values (53, '케이크·디저트', 7, false);
INSERT INTO category (id, title, parent_id, deleted) values (54, '주스', 7, false);
INSERT INTO category (id, title, parent_id, deleted) values (55, '스무디', 7, false);
INSERT INTO category (id, title, parent_id, deleted) values (56, '스프레드', 7, false);
INSERT INTO category (id, title, parent_id, deleted) values (57, '유제품·커피', 7, false);
INSERT INTO category (id, title, parent_id, deleted) values (58, '기타간식', 7, false);
INSERT INTO category (id, title, parent_id, deleted) values (59, '반찬가게', 8, false);
INSERT INTO category (id, title, parent_id, deleted) values (60, '반찬장인', 8, false);
INSERT INTO category (id, title, parent_id, deleted) values (61, '셰프의요리', 8, false);
INSERT INTO category (id, title, parent_id, deleted) values (62, '전국맛집', 8, false);
INSERT INTO category (id, title, parent_id, deleted) values (63, '키즈관', 8, false);


INSERT INTO promotion (id, promotion_type, title, description, original_price, final_price) values (30, 'SUB_DISH', 'pizza', '곧 죽어도 피자', 7000, 5000);
INSERT INTO promotion (id, promotion_type, title, description, original_price, final_price) values (31, 'SUB_DISH', '피자', '곧 죽어도 피자', 7000, 5000);
INSERT INTO promotion (id, promotion_type, title, description, original_price, final_price) values (32, 'SUB_DISH', '갓자', '곧 죽어도 피자', 7000, 5000);
INSERT INTO promotion (id, promotion_type, title, description, original_price, final_price) values (33, 'SUB_DISH', '피갓', '곧 죽어도 피자', 7000, 5000);
INSERT INTO promotion (id, promotion_type, title, description, original_price, final_price) values (34, 'SUB_DISH', '킹자', '곧 죽어도 피자', 7000, 5000)

INSERT INTO promotion (id, promotion_type, title, description, original_price, final_price) values (35, 'MAIN_DISH', '피자', '곧 죽어도 피자', 7000, 5000);
INSERT INTO promotion (id, promotion_type, title, description, original_price, final_price) values (36, 'MAIN_DISH', 'pizza', '곧 죽어도 피자', 7000, 5000);
INSERT INTO promotion (id, promotion_type, title, description, original_price, final_price) values (37, 'MAIN_DISH', '도미노', '곧 죽어도 피자', 7000, 5000);
INSERT INTO promotion (id, promotion_type, title, description, original_price, final_price) values (38, 'MAIN_DISH', '피자헛', '곧 죽어도 피자', 7000, 5000);
INSERT INTO promotion (id, promotion_type, title, description, original_price, final_price) values (39, 'MAIN_DISH', '미스터', '곧 죽어도 피자', 7000, 5000);
INSERT INTO promotion (id, promotion_type, title, description, original_price, final_price) values (40, 'MAIN_DISH', '임실', '곧 죽어도 피자', 7000, 5000);

INSERT INTO promotion (id, promotion_type, title, description, original_price, final_price) values (41, 'SOUP_AND_STEW', 'pizza', '곧 죽어도 피자', 7000, 5000);
INSERT INTO promotion (id, promotion_type, title, description, original_price, final_price) values (42, 'SOUP_AND_STEW', 'pizza', '곧 죽어도 피자', 7000, 5000);
INSERT INTO promotion (id, promotion_type, title, description, original_price, final_price) values (43, 'SOUP_AND_STEW', 'pizza', '곧 죽어도 피자', 7000, 5000);
INSERT INTO promotion (id, promotion_type, title, description, original_price, final_price) values (44, 'SOUP_AND_STEW', 'pizza', '곧 죽어도 피자', 7000, 5000);
INSERT INTO promotion (id, promotion_type, title, description, original_price, final_price) values (45, 'SOUP_AND_STEW', 'pizza', '곧 죽어도 피자', 7000, 5000);
INSERT INTO promotion (id, promotion_type, title, description, original_price, final_price) values (46, 'SOUP_AND_STEW', 'pizza', '곧 죽어도 피자', 7000, 5000);
INSERT INTO promotion (id, promotion_type, title, description, original_price, final_price) values (47, 'SOUP_AND_STEW', 'pizza', '곧 죽어도 피자', 7000, 5000);
INSERT INTO promotion (id, promotion_type, title, description, original_price, final_price) values (48, 'SOUP_AND_STEW', 'pizza', '곧 죽어도 피자', 7000, 5000);

